server:
  port: ${port:8072} #服务端口
spring:
  application:
    name: miniodemo #指定服务名
  profiles:
    active: production
  zipkin:
    base-url: ${zipkinUrl:http://qogir-zipkin:9411} #链路监控服务器url
  sleuth:
    sampler:
      probability: 0.1 #链路监控采样率，生产环境请改为0.1
  jackson:
    serialization:
      write-dates-as-timestamps: true

eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址     
      defaultZone: ${defaultZone:http://admin:admin@qogireureka:6868/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
feign:
  hystrix:
    enabled: true


hystrix:
  threadpool:
    default:
      coreSize: 200

